### ISSUE TITLE
Potential for official Fedora packaging

### ISSUE THREAD

**Issue by ldelossa** [wmww/gtk4-layer-shell#32]
Hello.

I'm now using gtk4-layer-shell in a project. 

It would be beneficial to install this library via a standard 'dnf install' like we can with the gtk3 version.

Are there plans to support this?

**Comment by wmww** [comment]
Hi, all the distro packaging for both libraries is done by other people. Your best bet might be to look up who maintains the gtk3 version packaging and ask if they're also willing to do gtk4-layer-shell version. You could also do the packaging yourself.

contact info seems to be here: https://packages.fedoraproject.org/pkgs/gtk-layer-shell/gtk-layer-shell/

**Comment by ProbstDJakob** [comment]
I've contacted the maintainer and as soon as there are new informations I will post them here.

**Comment by ProbstDJakob** [comment]
The maintainer of the `gtk-layer-shell` fedora package is willing to publish a package for `gtk4-layer-shell` and initiated the process but needs some help with the review and the tests. I will look into the failing tests and if needed will look into fixing the problems or opening a separate issue. Help by someone with more insight is highly appreciated.

- https://discussion.fedoraproject.org/t/gtk4-layer-shell-library-to-create-panels-and-other-desktop-components-for-wayland/114490
- https://bugzilla.redhat.com/show_bug.cgi?id=2277337

**Comment by wmww** [comment]
Don't worry about the lua smoke test, that one's been trouble on other distros as well, and I don't think signifies any real problem on our end. the other smoke tests seem to be failing because they're looking for things in the wrong place or things that aren't being build or something.

**Comment by ProbstDJakob** [comment]
I've send the maintainer a patch file containing the following comment (and just found out, that he applied the patch).

> ```
> # Disable smoke tests since they introduce two problems:
> #   1. They need the examples which will be installed and check-files fails with
> #      the error 'Installed (but unpackaged) file(s) found'
> #   2. The lua-lgi package is based on the (latest) release from 2017 which does
> #      not work with GTK4.
> # See also:
> #   - https://github.com/wmww/gtk4-layer-shell/issues/28
> #   - https://github.com/lgi-devs/lgi/issues/225
> #   - https://github.com/lgi-devs/lgi/issues/278
> ```

I've never packaged anything for Fedora nor did I work with meson before, thus there may be a better solution. For those who do not know what `check-files` is. It seems to be a program checking if all files installed by the build operation have been selected to be packaged, but since the examples should not be packed but got installed by meson, in order for the smoke tests to work, `check-files` failed.

Before I disabled all smoke tests, I've tried to get the lua smoke test to work. But this seems to be impossible because the only way to get it working (I have not tried it) is to check out the git repository. The problem is, that in the Fedora packaging process you do not have any internet access, thus you have to add the git repository as source for the package and this should not be done. I've then used `sed` to get rid of the lua smoke test, which is not pretty and if in the future the other smoke tests will be re-enabled, there should be an option to disable the lua smoke test without patching the `meson.build` file (I am aware of the issue https://github.com/wmww/gtk4-layer-shell/issues/28).

The only thing to be done in order to get a packaged version for Fedora is to [review the package request](https://bugzilla.redhat.com/show_bug.cgi?id=2277337) (I think).

**Comment by ldelossa** [comment]
Could this ticket be opened until the package is available in DNF? Would be a bit useful for me, since its a bit confusing watching the goings-on but the ticket being closed.

**Comment by ProbstDJakob** [comment]
The package has been accepted and is currently in the `updates-testing` repo.

**Comment by ProbstDJakob** [comment]
The package is now (1/2 days ago) in the `stable` repo.
