### ISSUE TITLE
Upstreaming into GTK?

### ISSUE THREAD

**Issue by Conan-Kudo** [wmww/gtk4-layer-shell#43]
Have you considered upstreaming it into GTK proper? I briefly talked to @matthiasclasen about this yesterday and he didn't seem against the idea of having layer-shell supported in GTK itself.

**Comment by wmww** [comment]
In the early development of the GTK3 version and then again when starting the GTK4 port myself and others who looked into it got a lot of pushback from GTK. Ultimately I concluded writing some shims and doing dynamic library hackery would be easier than winning arguments on IRC, so that's what I went with.

I'd be perfectly happy if this project was made irrelevant by upstream or somebody contributing to upstream, but I'm not going to dedicate any of my cycles to this.

**Comment by wmww** [comment]
See [here](https://github.com/wmww/gtk-layer-shell/issues/37) and [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/2132) for some of the history, though I'm not sure how much of what you'll find there is still relevant.

**Comment by ids1024** [comment]
And https://github.com/wmww/gtk4-layer-shell/issues/9, though that mainly just links the same things.

I think it would be possible to land the minimum necessary changes required to accommodate this in GTK. Though it's nontrivial. I'm not really working with GTK4 anymore, but if anyone's interested I can try to offer some suggestions from what I remember of this.

**Comment by wmww** [comment]
Oh yeah, I looked for that issue but didn't see it for some reason. If anything were to be upstreamed, just doing enough API to allow for better 3rd party surface types seems like the best way to do it to me.

**Comment by ids1024** [comment]
Yeah. It would also be good to support `ext_session_lock_surface_v1` and other possible surface types. And it might not make sense to support those all in GTK. But a non-hacky way for libraries to do it would be nice.

**Comment by Conan-Kudo** [comment]
When I talked to @matthiasclasen about it, he seemed like he wanted it directly supported in GTK in some way rather than having GTK overlay modules like this one.
